### ISSUE TITLE
Error: Unhandled exception rendering component: Cannot read properties of null (reading 'removeChild')

### ISSUE THREAD

**Issue by bryanrcarlson** [CafIncubator/Midden#69]
Reproduce:

In Catalog, click the preview button, then click the "View Page" button.

The follow is the error message:

```
blazor.webassembly.js:1 
        
       crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Cannot read properties of null (reading 'removeChild')
      TypeError: Cannot read properties of null (reading 'removeChild')
          at e (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:10331)
          at e (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:10303)
          at Object.e [as removeLogicalChild] (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:10303)
          at e.applyEdits (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:33040)
          at e.updateComponent (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:32271)
          at Object.t.renderBatch (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:12134)
          at Object.window.Blazor._internal.renderBatch (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:61913)
          at Object.w [as invokeJSFromDotNet] (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:64435)
          at _mono_wasm_invoke_js_blazor (https://meta.cafltar.org/_framework/dotnet.5.0.9.js:1:190800)
          at wasm_invoke_iiiiii (wasm://wasm/00aba242:wasm-function[5611]:0xdda7f)
Microsoft.JSInterop.JSException: Cannot read properties of null (reading 'removeChild')
TypeError: Cannot read properties of null (reading 'removeChild')
    at e (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:10331)
    at e (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:10303)
    at Object.e [as removeLogicalChild] (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:10303)
    at e.applyEdits (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:33040)
    at e.updateComponent (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:32271)
    at Object.t.renderBatch (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:12134)
    at Object.window.Blazor._internal.renderBatch (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:61913)
    at Object.w [as invokeJSFromDotNet] (https://meta.cafltar.org/_framework/blazor.webassembly.js:1:64435)
    at _mono_wasm_invoke_js_blazor (https://meta.cafltar.org/_framework/dotnet.5.0.9.js:1:190800)
    at wasm_invoke_iiiiii (wasm://wasm/00aba242:wasm-function[5611]:0xdda7f)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

Likely an issue with modal component?

**Comment by bryanrcarlson** [comment]
Addressed in #72
